### ISSUE TITLE
PEP8 violation of module names

### ISSUE THREAD

**Issue by JustinTervala** [pgmpy/pgmpy#1006]
### Subject of the issue
According to the "[Package and Module Names](https://www.python.org/dev/peps/pep-0008/#id40)" section of PEP8, "Modules should have short, all-lowercase names." This is standard across almost all Python style guides. Is there a reason this is violated in this codebase? Other than introducing aliased versions of the existing UpperCamelCase module names, I'm not sure how to fix this issue without causing a massive backward-breaking change.

### Expected behaviour
According to PEP8, modules should be named with lower camel case 

### Actual behaviour
Modules are named with UpperCamelCase

**Comment by ankurankan** [comment]
@JustinTervala There's no specific reason for it. We started the package like that and it just stuck and we never changed it after that. I don't think changing the module names would break anything because most of our `__init__.py` files directly import the classes, so I don't think the user really needs to explicitly specify the module name (other than some exceptions).
