### ISSUE TITLE
BN Inference takes huge memory and takes long

### ISSUE THREAD

**Issue by karnatapu** [pgmpy/pgmpy#1051]
### Inference takes enormous memory and takes a while

Hello, I do have a Bayesian model of 30 nodes and fitted with data using MLE. Each node cardinals ranges between 2-10 states, but most of them are 2 (60%). Am able to quickly get the the CPD for each node. However when a run the inference using Variable-Elimination by giving an evidence, it takes huge memory (in gigs ) and takes 3-10 minutes to get the results. 

inference = VariableElimination(model)
phi_query = inference.query(variables=['A''], evidence= {'evidence01':0 })

if I add more variables to the same query, memory consumption increases exponentially and sometime it uses full peak memory of 16GB and sporadically gets Memory error. 

phi_query = inference.query(variables=['A', "B","C","D"......"K"], evidence= {'evidence01':0 })

Basically I need to get the probabilities of all the nodes (marginal) given an evidence. If you have any alternative way, please let me know.

Also I did tried using BeliefPropagation, it takes even more time to spit the results (didn't ran more than an hour)

Questions:
1. Do you have any place where we can add any type of cache (LRU_cache) to do better memory management and  speedup the process.

2. Technically belief-progation supposed to be fast as it is approximation and uses junction tree. However Variable elimination doing much better. Would other inference methods (MRLP, dynamic BN inference) gets faster and less memory footprint results

3. Why evidence object takes dictionary values as indexes, which is integer rather than actual state of the variable. For example: 'Status' variable have the states of 'active' and 'inactive'. When i try to do the inference with evidence it is allowing me to do label encoding value as 0 or 1. 
phi_query = inference.query(variables=['A''], evidence= {'status':0 })

instead I would like to do as below. Is there any way?
phi_query = inference.query(variables=['A''], evidence= {'status':'active' })

Thanks

as variables get increases

### Your environment
* pgmpy version - latest
* Python version - 3.6
* Operating System - windows latest

### Expected behaviour
Memory efficient

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
@karnatapu Internally we compute the joint distribution over all the variables that you pass in the query and at the end marginalize over the variables to give out the final result dict. We do that to save on computation (by using more memory) by not doing elimination on all the common variables from each of the variable passed in the query. In your case I would suggest you to do an explicit for loop and run query on single variables. 

Belief Propagation is slow because it also does exact inference (but has the benefit of using less memory on huge structures), we still don't have an implementation for an approximate algorithm.

And evidence should accept state names. I will create an issue for that.
