### ISSUE TITLE
Refactor DirectedGraph class

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#1064]
### Subject of the issue
`DirectedGraph` is currently the base class for all the DAG-based models. It should be renamed to `DAG` to be more explicit and all the DAG methods should be moved from `BayesianModel` to `DAG` as they are applicable to all DAG based models. The following changes need to be done (along with their tests):

- [x] Rename `DirectedGraph` to `DAG`
- [x] Add checks for cycles in `DAG.__init__`
- [x] Move `BayesianModel.active_trail_nodes` method
- [x] Move `BayesianModel.local_independencies` method
- [x] Move `BayesianModel.is_active_trail` method
- [x] Move `BayesianModel.get_independencies` method
- [x] Move `BayesianModel.get_immoralities` method
- [x] Move `BayesianModel.is_iequivalent` method
- [x] Move `BayesianModel.get_markov_blanket` method
- [x] Make sure structure learning algorithms learn a `DAG` instance instead of `BayesianModel` instance.

### Your environment
* pgmpy version: All
* Python version: All
* Operating System: All

**Comment by mackeper** [comment]
Hello, we are five people reading a course in software engineering and our current assignment is to solve a refactoring issue in an open-source project. We chose this one because it felt doable, it is nicely documented and we have prior knowledge about graphs. 

We only have a few days to finish this so we might not be completely finished but we must announce that we are working on this issue as a requirement of the course. Hopefully, there will come a pull request soon but we can not ensure this.

:smile:

**Comment by ankurankan** [comment]
@mackeper Great. Let me know if you need any help with this.

**Comment by gpihl** [comment]
Hi @ankurankan I am also in the group who is going to be working on the issue. I'm just wondering two things:
- What should happen if the graph passed to the constructor has cycles?
- Would you perhaps be able to list the structure learning algorithms that are to be modified to use DAGs instead of BaysianModels?

Thanks!

**Comment by mackeper** [comment]
@ankurankan We have one question, what do you want  DAG.__init__ to do if a cycle is found?

**Comment by ankurankan** [comment]
@gpihl 
* What should happen if the graph passed to the constructor has cycles?
This should just raise a `ValueError` and if possible the error message should also include the cycle.
* Would you perhaps be able to list the structure learning algorithms that are to be modified to use DAGs instead of BaysianModels?
1. `pgmpy.estimators.ConstraintBasedEstimator`
2. `pgmpy.estimators.ExhaustiveSearch`
3. `pgmpy.estimators.HIllClimbSearch`

**Comment by gpihl** [comment]
Perfect, thanks!

**Comment by mackeper** [comment]
@ankurankan When we rename `DirectedGraph` to `DAG` we no longer have a data structure to represent a PDAG, how would you like to handle this?

**Comment by ankurankan** [comment]
@mackeper As far as I remember the representation part of pdag is done in `ConstraintBasedEstimator` and shouldn't require any changes elsewhere. Could you point me to exactly where you are running into issues?

**Comment by mackeper** [comment]
@ankurankan The problem is with the function `pdag_to_dag(pdag)` which takes a DirectedGraph as input and now if we rename DirectedGraph to DAG here it does not make sense.

The issue can be solved by letting the function instead take a networkx.DiGraph as input and change the following test: [test_ConstraintBasedEstimator](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/tests/test_estimators/test_ConstraintBasedEstimator.py)
```
def test_pdag_to_dag(self):
        pdag1 = DirectedGraph([('A', 'B'), ('C', 'B'), ('C', 'D'), ('D', 'C'), ('D', 'A'), ('A', 'D')])
```
to

```
def test_pdag_to_dag(self):
        pdag1 = nx.DiGraph([('A', 'B'), ('C', 'B'), ('C', 'D'), ('D', 'C'), ('D', 'A'), ('A', 'D')])
```

What do you think about this solution?

**Comment by ankurankan** [comment]
@mackeper I think the best solution would be to create a new class to represent PDAGs. Since PDAGs are a different data structure and have both directed and undirected edges. We have been representing PDAGs using directed graph by having edges in both directions to represent an undirected edge. This would also mean that the `ConstraintBasedEstimator.skeleton_to_pdag` method should return a PDAG instance and  `ConstraintBasedEstimator.pdag_to_dag` method should accept a PDAG instance and return a DAG instance.
