### ISSUE TITLE
What are the scale limits of `pgmpy`?

### ISSUE THREAD

**Issue by NoamGit** [pgmpy/pgmpy#1078]
Hi,

I am about to have a relatively big dataset (100K rows) with about 200 features and lots of edges. I was considering pgmpy as the bayesnet constructor and engine.
Can it handle this about of data and features? What are its empirical limits? Are there any recommended substitutes for this task?

Thanks

**Comment by khalibartan** [comment]
Since pgmpy uses multi-dimensional numpy arrays for representing CPDs, if a CPD has more than 32 variables (31 parents) then you won't be able to use pgmpy.

**Comment by ankurankan** [comment]
@NoamGit It's really hard to come up with exact numbers for the limits. In general, the problems happen when there are a lot of parent nodes of some variable or if some variables have a lot of states (because of the exponential size of CPDs). In general, there are some methods to deal with these situations like parent divorcing or binning variable states.

Also as @khalibartan mentioned pgmpy doesn't support variables with more than 31 parent nodes (because of numpy's restriction of max 32-dimensional matrices). Also, a single CPD with 31 parent variables with each having just 2 states would take up 16GBs of memory to store, so the only solution to these problems is to modify the network structure.

I don't know of any other python packages unless you want to use some special case Bayesian network (like Naive Bayes etc). A popular R package is `bnlearn` which you can give a try but again the main limitation is usually the machine's memory in case of complex networks.

**Comment by NoamGit** [comment]
Thanks!
I know It would be tremendously harder, but do you think that using `pyMC3`, `pyro` (Uber) or `tensorflow-probalistic` (Edward) would enable to work this up?

Also, do you imply that we should consider building a network with a maximum of 31 parents per feature/node?

**Comment by ankurankan** [comment]
@NoamGit I assumed in my last comment that you are working with discrete variables. If you are working with continuous distributions, things will be much easier. You should be able to use pymc or tensorflow-probability (I don't have any idea about pyro), but since in both these cases you will have to work with joint distributions, you won't have other functionality of Bayesian Networks.

The number of parents wouldn't be a big issue in case of continuous distributions, but in the discrete case 32 parents in quite big and I would suggest something way smaller.

**Comment by NoamGit** [comment]
Thanks again,
Do you have an example of a mixed network, both with continuous and discrete? 
Let's say that in a medical diagnosis model I have both the sex:`bool`, age_binned:`Discrete`, heart_rate:`Continous` and medication:`Discrete`, and I want to model some condition. 

- Would it be wise to preprocess the data, s.t. it will have low cardinality per feature?
- Should I model the continuous variable by simply looking at the empirical distribution and approximate to some pdf with cherrypicked parameters? Do you have an example of that?
- Also, I guess that in a big network exact inference, such as in Variable Elimination, won't be plausible, so I simply use rejection sampling for "What if?" queries. Does this seem right?

Sorry for all these questions...I am fairly inexperienced in this domain

**Comment by ankurankan** [comment]
@NoamGit Sorry for the late reply. pgmpy doesn't have support for continuous variables. And hybrid models (continuous + discrete variables) is one of the most difficult cases to deal with and in my experience even `bnlearn` has very limited support for it. So, a general workflow is usually to convert all the variables to either continuous (continuous is preferred because of nicer statistical properties) or discrete. Also for the distributions of the continuous variable, we usually stick to one of the conjugate distributions (gaussian or multinomial mostly) for closed form computations. But if you want to use other distributions you can always treat the model as a joint distribution and use probabilistic programming tools like pymc3 to do inference on it.

**Comment by NoamGit** [comment]
Thanks!

Off topic newbie question -  (In case of moving to a continuous representation) **Given a dataset and a graph structure, how should I model the BN with probabilistic programming?** Are there any guidelines to decide the variable interactions for the joint probs when they are not CPT but CPD?

Are you familiar with an example to set the priors or the joint distribution? I didn't come across something, that doesn't rely on a predefined relationship between variables.
So far I've gone over the following examples - 
https://github.com/usnistgov/pmml_pymcBN/blob/master/presentation/presentation.ipynb
https://gist.github.com/tbsexton/1349864212b25cce91dbe5e336d794b4
http://people.duke.edu/~ccc14/sta-663-2017/19A_PyMC3.html

**Comment by ankurankan** [comment]
@NoamGit Bayesian Networks represents a joint distribution which is the product of all the CPDs in the network. So, if you have the structure you can start by learning these CPDs (variable given it's parents). You will have to decide the learning method that you want to use (Maximum Likelihood, Bayesian Estimation etc). You wouldn't need any prior for Maximum Likelihood, but for Bayesian Estimation you will need to have a prior which really depend on the variables/problem (a common strategy is to have a uniform distribution as the prior if you don't have any information about the variables)(https://stats.stackexchange.com/a/78629/46298). Once you have these CPDs, you can do inference over the network by doing inference on the product of all the CPDs. The probabilistic programming tools will allow you to represent these CPDs and their product, and will allow to do inference (by sampling or Variational Inference). Hope this helps :)
