### ISSUE TITLE
Belief propagation for large networks. IndexError in product phi.values = phi.values[slice_].

### ISSUE THREAD

**Issue by dekelio** [pgmpy/pgmpy#1110]
### Belief propagation error for large networks give IndexError in product phi.values = phi.values[slice_].
Hi, I'm using belief propagation with 2 evidence nodes and ~700 query nodes. My graph is acyclic and each node has single parent. When I reduce the size of the network to 20 nodes or less it works fine.
 
[This](https://github.com/pgmpy/pgmpy/issues/813) and [this](https://github.com/pgmpy/pgmpy/issues/1044) issues looks similar. 

### Environment
* pgmpy version 0.1.6
* Python version 2.7
* Operating System Ubuntu 16.04

### Steps to reproduce
I'm adding the cpt's from a dictionary so I don't have a simple way to reproduce from scratch, but here are the code parts that are pgmpy related. 

```
def define_model_structure(pairs):
    ps = []
    [ps.append((str(p[0]), str(p[1]))) for p in pairs]
    listener_model = BayesianModel(ps)
    return listener_model
```
```
def define_network_parameters(pair_to_cpd, root_ind, p_root):
    cpds = dict()
    cpds[str(root_ind)] = TabularCPD(variable=str(root_ind), variable_card=2,
                                     values=[[1-p_root], [p_root]])
    for k, v in pair_to_cpd.items():
        parent, child = str(k[0]), str(k[1])
        cpds[child] = TabularCPD(variable=child, variable_card=2, values=v,
                                 evidence=[parent], evidence_card=[2])
    return cpds
```
```
def associate_parameters_with_structure(listener_model, cpts):
    for i in cpts.values():
        listener_model.add_cpds(i)
    assert listener_model.check_model()
```
```
def set_network_structure_and_parameters(sorted_graph, c22, idx_to_label, singles):
    root_node = get_root(sorted_graph)
    c_root = c22[idx_to_label[root_node] + ':' + idx_to_label[root_node]]
    num_images = np.sum(c_root)
    p_root = float(singles[idx_to_label[root_node]]) / num_images
    pairs_to_cpt = get_graph_cpds(sorted_graph, c22, idx_to_label)
    listener_model = define_model_structure(pairs_to_cpt.keys())
    cpts = define_network_parameters(pairs_to_cpt, root_node, p_root)
    associate_parameters_with_structure(listener_model, cpts)
    return listener_model
```
```
listener_model = infer.set_network_structure_and_parameters(sorted_tree, c22_dict, ind_to_label, singles)
bp = BeliefPropagation(listener)
bp.calibrate()
q = bp.query(variables=q_vars, evidence=e_vars)
```
### Expected vs. actual behaviour 
expect to get the marginals for all the nodes that are not evidence but I'm getting the following error: 

> pgmpy/factors/discrete/DiscreteFactor.py", line 586, in product phi.values = phi.values[slice_] IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by ankurankan** [comment]
@liorbracha I think this is happening because you have around 700 query variables and pgmpy internally computes the joint distribution over all the query variables and then returns the marginalized results over each variable. But since numpy has a limitation of 32 dimensional matrices, we cannot represent a CPD with more than 32 variables. 

I think you can make it work by using `VariableElimination` and providing an `elimination_order` for each variable in `q_vars` separately. Since you have a chain graph, you can easily compute a very efficient elimination order. Something like [topologically sorted ancestors till an evidence var/root node + reverse topologically sorted descendents till an evidence variable/leaf node] of the queried variable. This would allow you to keep the CPD sizes small so will run much faster.

**Comment by dekelio** [comment]
Got it. Thanks for the quick reply!
