### ISSUE TITLE
VariableElimination ignores identical factors

### ISSUE THREAD

**Issue by rballester** [pgmpy/pgmpy#1261]
### Subject of the issue
When VariableElimination generates several identical factors (same variables, same values) only one is considered and the rest are discarded. This is due to the use of sets (see e.g. "final_distribution = set()" in ExactInference.py), which do not admit repeated elements. 

This can be fixed by switching to another data structure. I would have time, but which one? Python lists, a multiset using collections.Counter?

This issue (identical factors arising during variable eliimination) will rarely be a problem for learned networks --but it can be academic examples. May be related to other inference problems (issue #856 ?).

### Environment
* pgmpy version: 0.1.10
* Python version: 3.6.10
* Operating System: Ubuntu 18.04

### Steps to reproduce
    import numpy as np
    from pgmpy.models import MarkovModel
    from pgmpy.factors.discrete import DiscreteFactor
    from pgmpy.inference import VariableElimination

    g = MarkovModel([('A', 'B'), ('A', 'C')])
    f1 = DiscreteFactor(variables=['A', 'B'], cardinality=[2, 2], values=np.eye(2) * 2)
    f2 = DiscreteFactor(variables=['A', 'C'], cardinality=[2, 2], values=np.eye(2) * 2)
    g.add_factors(f1, f2)

    print(VariableElimination(g).query(['A']))  # <- gives incorrect result: [2, 2]

    # We now modify one of the factors by a tiny amount, so they are no longer equal
    g.factors[0].values += 1e-8
    print(VariableElimination(g).query(['A']))  # <- gives correct result: [4, 4]

**Comment by ankurankan** [comment]
@rballester Thanks a lot for reporting this. You are right, using `sets` seems to be the culprit here. I think the main fix here would be to change the way `working_factors` is implemented right now. Currently, it's a dict of `{variable: set of all factors involving the variable}`, so it automatically removes all duplicate intermediate factors during the inference.

I would guess that Counter should be able to give us a cleaner and faster implementation compared to using lists as we would need to do search and add/remove factors during the run. What do you think?

**Comment by rballester** [comment]
@ankurankan Thank you for developing pgmpy! The Python community desperately needs good statistical tools, and this project is a ray of hope.

I will look into Counter and issue a PR.
