### ISSUE TITLE
anyone meet this same error with me?

### ISSUE THREAD

**Issue by MrYu001** [pgmpy/pgmpy#1324]
### Subject of the issue
when i use pgmpy do the job that realize the causal inference by dynamic bayesian network,  
and the method is the 'dbn_inference'.
and when the two values of the evidence_card are not same, like as follows:
z_trans_cpd = TabularCPD(('Z', 1), 2, [[0.4, 0.7 0.8 0.3],
                                              [0.6, 0.3 0.2 0.7]],
                              evidence=[('Z', 0),('B',0)],
                              evidence_card=[2,3])

and the procedure will get an error.
but when the two values are same, will not get the same error again like this:
z_trans_cpd = TabularCPD(('Z', 1), 2, [[0.4, 0.7 0.8 0.3],
                                              [0.6, 0.3 0.2 0.7]],
                              evidence=[('Z', 0),('B',0)],
                              evidence_card=[2,2])
### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
@MrYu001 The `dbn_inference` method does probabilistic inference, causal inference for Dynamic Bayesian Networks is not supported yet. The error that you are getting is because of the shape of the values array. The CPD requires the values array to be of the shape (no of states/cardinality of variable, product of no of states/cardinality of parents). In the first case, this means that the shape should be (2, 2x3) but the given value is of shape (2, 4), hence the error. The shape in the second case is correct as: (2, 2x2).

**Comment by MrYu001** [comment]
i don't undertand what you mean that the pgmpy can not support dbn now,  and my issue is about the situation that when the two parents nodes of a specified one get different Possible values, the forward_inference in dbn get error.

**Comment by ankurankan** [comment]
@MrYu001 I meant that causal inference for DBN is not implemented yet. For doing causal inference for DBN, you will have to manually convert it to a BayesianModel and work with it. You are getting the error because you have specified a wrong CPD. The shape of the array that you have passed is not correct in the 1st case.
