### ISSUE TITLE
How to combine BayesianNetwork and NoisyOR ? 

### ISSUE THREAD

**Issue by hejunqing** [pgmpy/pgmpy#1355]
### Subject of the issue
I want to build a 3-layer BN with the last layer being the NoisyOR nodes, how could I accomplish that?
I constructed a BayesianNetwork and found that I could not customize the computation of the NoisyOR nodes. All I can do is to assign CPDs.

### My environment
* pgmpy version 0.1.12
* Python version 3.6.5
* Operating System: Centos 7.4

### my code
from pgmpy.models import BayesianModel,NoisyOrModel
```
directed_pairs=get_node_pairs() # get structures
model=BayesianModel(directed_pairs)
```
Then model only has .add_cpds() method

But if I use NoisyOrModel，I can only add_variables and del_variables.

### Expected model
I want to build a 3layer model. The first layer is composed of nodes R={r_1,r_2,...r_m} which point to the second layer of nodes D={d_1,d_2,...,d_n}. They form a two layer BN. Then D point to nodes S ={s_1,s_2,...,s_i}, which is a Noisy OR layer. What should I do to construct such a model and inference on it?

**Comment by ankurankan** [comment]
@hejunqing The `NoisyOrModel` isn't complete and there is no direct way to combine it with `BayesianModel` yet. But since the `NoisyOrModel` is just a special case of Bayesian model, in which you specify the CPDs to have high probabilities for some specific causes, and the other probabilities are very small (or 0). So, you can basically define the CPDs in Bayesian Model which will be able to simulate Noisy Or behavior. I found an example of how the CPDs should look for Noisy Or here: https://link.springer.com/content/pdf/10.1007%2F978-3-642-22152-1_11.pdf  (section 2.1) which might be helpful.
