### ISSUE TITLE
How to check I-equivalent graphs ?

### ISSUE THREAD

**Issue by SachiniEMSPE** [pgmpy/pgmpy#1458]
Hi @ankurankan , 
I installed the latest dev version of pgmpy and tried to check the I-equivalent of 3 simple graphs (this time a different graph) using `is_iequivalent`.  But, I'm getting an unexpected result again for my example. I was expecting G2 to be **not an I-equivalent graph of G**, **because of different v-structure** (instead here I'm getting True). I'm following the rule: t_he same skeleton and same V-structure are required to be an I-equivalent graph._ But, this result seems to be a little bit confusing to me again. I would highly appreciate any help to understand this.  Thanks ! 

* pgmpy version 0.1.11
* Python version 3.8
* Operating System Windows

### Steps to reproduce
```
G = DAG()
G.add_edges_from([('R', 'S'), ('R', 'G'),('S','G')]) #original network
G1 = DAG()
G1.add_edges_from([('S', 'R'), ('R', 'G'),('S','G')]) 
G2 = DAG()
G2.add_edges_from([('R', 'S'), ('G', 'R'),('G','S')]) 
G3 = DAG()
G3.add_edges_from([('R', 'G'),('S','G')]) 
print(G.is_iequivalent(G1))
print(G.is_iequivalent(G2))
print(G.is_iequivalent(G3))
```

### Expected behaviour
```
True
False
False
```
### Actual behaviour
```
True
True
False
```

**Comment by ankurankan** [comment]
@SachiniEMSPE I think the results are correct. Even though the v-structure is different in the two models, there are no implied independencies in either of G, G1, and G2 because of the additional edge (R -> S in G; S -> R in G1; G -> R is G2)  between the parents of the collider variable. Hence they are i-equivalent. G3 does have the implied independence of `R _|_ S`, hence it returns false. You can also verify this using the `get_independencies` method:
```
In [3]: G.get_independencies()
Out[3]: 

In [4]: G1.get_independencies()
Out[4]: 

In [5]: G2.get_independencies()
Out[5]: 

In [6]: G3.get_independencies()
Out[6]: 
(R ⟂ S)
(S ⟂ R)

```

**Comment by SachiniEMSPE** [comment]
Oh I see... yeah now it's clear! Thank you so much! 😀
