### ISSUE TITLE
Likelihood in estimators like EM

### ISSUE THREAD

**Issue by dagap** [pgmpy/pgmpy#1469]
I was looking at the source code for the EM estimator and particularly the function `def _get_likelihood(self, datapoint):`

The line:

```
likelihood *= cpd.get_value(
                    **{key: value for key, value in datapoint.items() if key in scope}
                )
```

Why is it that you work directly with raw likelihoods rather than the log of it. Would using the log not result in better numerical stability?

**Comment by ankurankan** [comment]
@dagap Yes, using log-likelihood would definitely be better for numerical stability. But I would like that to be added a bit systematically (instead of doing it just for say EM) as other parts of code can benefit from using log values as well. I think a good idea could be to add a LogDiscreteFactor class, which has all the methods of the DiscreteFactor class but works on log values. 
That should allow us to easily choose between doing operations on log-scale or probability values.

**Comment by dagap** [comment]
@ankurankan Thanks for that. Definitely makes sense to make a systematic update. Is it something planned in the future?

**Comment by ankurankan** [comment]
@dagap I don't have an exact plan/timeline on this as I don't think I will have the bandwidth to work on this anytime soon. But I would be more than happy to help if you or someone else would like to take up on this.

**Comment by dagap** [comment]
@ankurankan I might have a look at this one weekend and do a pull request.

**Comment by ankurankan** [comment]
Great. Would be happy to help if you have any questions.
