### ISSUE TITLE
ValueError: Sum or integral of conditional probabilities for node <name> is not equal to 1

### ISSUE THREAD

**Issue by zzzrbx** [pgmpy/pgmpy#1696]
I occasionally get this warning:
```
 RuntimeWarning: invalid value encountered in true_divide
  tabular_cpd.values = (cpd / cpd.sum(axis=0)).reshape(tabular_cpd.cardinality)
```

which results into this error when making predictions:
`ValueError: Sum or integral of conditional probabilities for node <name> is not equal to 1.
`
Unfortunately I cannot share the data. any idea on how to degub/fix this problem? I'm currently using version 1.22.

**Comment by ankurankan** [comment]
@zzzrbx The warning is usually fine as the CPD values need to be adjusted at times due to numerical error. The only reason I can think of for the error is that there are NaN values in the CPD (unless the CPD was specified manually). It's hard to say why that could be happening without looking at the code, but that could be the starting point for debugging the issue.
