### ISSUE TITLE
Identity/ Unit Factor

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#171]
Implement the functionality to define an identity/ unit factor which when multiplied with any other factor returns the factor itself.

https://groups.google.com/forum/#!topic/pgmpy/IXKXb36bHmY

**Comment by ankurankan** [comment]
@navinchandak For Identity Factor you could simply use a Factor with the same variables and cardinality having all the values equal to 1.

Example:

``` python3
f1 = Factor(['x1', 'x2', 'x3'], [2, 3, 2], np.random.rand(12))
```

For this you can create the unit factor as:

``` python3
identity_factor = Factor(f1.variables, f1.cardinality, np.ones(12))
```

**Comment by navinchandak** [comment]
@ankurankan So in the case when I need it, I really don't know what I will be multiplying the unit factor with. It is basically the base case in a recursive function. So the above solution will not work.
(Ofcourse there are hacky solutions like passing a None and then not doing any mutiplication when we see a None, but they are hacky. A identity factor is the best solution)
And yes, identity factor is a better term for what I am looking for.

**Comment by ankurankan** [comment]
@navinchandak Show me the code where you need it.

**Comment by navinchandak** [comment]
@ankurankan Sorry I missed replying to this. So please go to the file 
https://github.com/navinchandak/pgmpy/blob/dev/pgmpy/MarkovModel/JunctionTree.py
Now if you see the _push function, I am passing an empty_factor which is just None to _push_h. And in _push_h, I am not doing the multiplication if the passed thing is None.(The effect is same as multiplying with a Identity Factor). It would be a good idea if I can pass something like an Identity Factor which will make things cleaner.

However, this issue is not on the priority list right now. We can handle this once the GSOC period is over. (Once I am done with GSOC work).

**Comment by ankurankan** [comment]
Fixed
