### ISSUE TITLE
Building docs locally - How-to

### ISSUE THREAD

**Issue by tillwenke** [pgmpy/pgmpy#1761]
### Subject of the issue
Following the description didnt create the docs for me. See: https://github.com/pgmpy/pgmpy/blob/4ab68bff2be3e858bb68096c66437bc81a391a7b/README.md?plain=1#L98

### Your environment
* Ubuntu 22.04

### Steps to reproduce
What I had to do before to execute `make html` was:
* `sudo apt-get install python3-sphinx`
* `pip install nbsphinx`

### Actual behaviour
Local built was stored in `../../pgmpy_docs/`

When built locally, the docs didnt show the description of the classes. Like: 
![image](https://github.com/pgmpy/pgmpy/assets/38500891/0619b850-e526-4d2e-b807-81b5341f724b)

**Comment by ankurankan** [comment]
@tillwenke Thanks for creating the issue. We have more details on building the docs here: https://github.com/pgmpy/pgmpy/wiki/Maintenance-Guide . I have also updated the README to refer to wiki now. I am not sure why you are not seeing the docs for Belief Propagation because the online website does show the docs (https://pgmpy.org/exact_infer/bp.html). Could you maybe try rebuilding using the steps in the wiki or maybe check if sphinx is throwing some warnings regarding this when building.

**Comment by tillwenke** [comment]
That helped.
When starting from I believe https://github.com/pgmpy/pgmpy/wiki/Maintenance-Guide does not include all details.
e.g. I had to install all pgmpy requirements as well.

Someone could investigate if following the steps in https://github.com/pgmpy/pgmpy/wiki/Maintenance-Guide results in a built documentation.

**Comment by tillwenke** [comment]
This issue is resolved for now. thanks.
