### ISSUE TITLE
Fix __repr__ of TabularCPD

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#265]
``` python
cpd_a = TabularCPD('A', 2, [[0.2], [0.8]])

cpd_a
Out[9]: 
A phi(A) ------------------ A_0 0.2000 A_1 0.8000 
```

**Comment by siteshjaiswal** [comment]
I want to work on this.Please add any furthur information needed to get me start.

**Comment by abinashpanda** [comment]
@siteshjaiswal The goal is to create a one-line description for `TabularCPD` class. For example

``` python
In [1]: cpd_a = TabularCPD('A', 2, [[0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                                    [0.9, 0.9, 0.9, 0.9, 0.9, 0.9]],
                           ['B', 'C'], [2, 3])

# __repr__ method should return something like this
In [2]: cpd_a
<TabularCPD representing P(A:2 |B:2, C:3) at 0x7f34ac8c5160>
```

The format `P(A:2 |B:2, C:3)` represents that it is a `TabularCPD` object representing conditional probability of `A` of cardinality 2, given `B` of cardinality 2 and `C` of cardinality 3 and `0x7f34ac8c5160` represents the memory location of this `TabularCPD` object. 

If there are no evidence then it should be simply

``` python
In [3]: cpd_b = TabularCPD('B', 2, [0.2, 0.8])
In [4]: cpd_b
<TabularCPD representing P(B:2) at 0x7f34ac8c5160>
```

Let me know if you have any doubts.

**Comment by siteshjaiswal** [comment]
@abinashpanda I have made some changes in`__repr__` of TabularCPD.
And i am getting return like this:
`In [3]: cpd_a`
`In [4]: <TabularCPD representing P(grade:3 |intel:3,diff:2)>`
instead of
`In [3]: cpd_a`
`In [4]: <TabularCPD representing P(grade:3 |intel:3,diff:2) at 0x7f34ac8c5160>`
I am unable to get memory address of cpd_a as suggested by you.
Please suggest some method to do so.
https://github.com/siteshjaiswal/pgmpy/commit/35d47817515240f5b94053b3774f95bf9a516cc6

**Comment by abinashpanda** [comment]
@siteshjaiswal Please send a PR with your current modifications. After that we can discuss on how to go further.

**Comment by ankurankan** [comment]
Fixed.
