### ISSUE TITLE
nosetest fails after fresh install

### ISSUE THREAD

**Issue by alisianoi** [pgmpy/pgmpy#322]
I am runing `Arch Linux`

``` sh
$ uname -a
Linux tardis 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux
```

I followed these [installation instructions](http://pgmpy.org/install.html). Specifically, my actions were:

``` sh
$ git clone https://github.com/pgmpy/pgmpy
$ cd pgmpy
$ virtualenv --system-site-packages vipgmpy
Using base prefix '/usr'
New python executable in vipgmpy/bin/python3
Also creating executable in vipgmpy/bin/python
Installing setuptools, pip...done.
$ source ./vipgmpy/bin/activate
$ python setup.py install
```

At this point, the `setup.py` finds all the required packages except one: `numpy`. That is because in `Arch Linux` the version of this package compiled with `openblas` support is called `numpy-openblas`. So, `setup.py` installs the vanilla `numpy` into the `vipgmpy` virtual environment. To be precise, here is the [verbose list of my dependencies](https://gist.github.com/all3fox/ff8a27901cae376519a0).

At this point everything is fine. I fire up `ipython`, issue `import pgmp`. It succeeds. So I decide to run the tests. From the source directory, I run `nosetests` and get a huge sheet of [failed tests](https://gist.github.com/all3fox/582fb271cb885fa72c53).

What am I doing wrong?

**Comment by ankurankan** [comment]
@all3fox Could you please check the version of networkx you are using?

**Comment by alisianoi** [comment]
@ankurankan Sure. As I mentioned in the [verbose list of my dependencies](https://gist.github.com/all3fox/ff8a27901cae376519a0), the version of `networkx` was `1.9.1` which is newer than `1.8.1` as required by the documentation. So, I installed the older one and all the tests now pass.

How much time do you think it will take to update to the newer version of the library? Might that be a viable GSoC 2015 commit for the _first commit_ rule of the PSF?

**Comment by ankurankan** [comment]
@all3fox: I think I have attempted this in past and wasn't able to fix it. But you can try to work on this and this can surely be counted as a patch.
 But I think you will need good amount of time for this since networkx is used in the whole codebase so you will have to get familiar with almost the whole codebase.

**Comment by alisianoi** [comment]
>  I have attempted this in past and wasn't able to fix it.

I see, then I will choose something else to start.

Would you be interested if updating to the latest version of this library was (perhaps, part of) my GSoC proposal?

**Comment by ankurankan** [comment]
@all3fox: No I don't think this would be a good GSoC project. Because you will need some time for this and because of the other changes happening  simultaneously, we will get a lot of conflicts. So I would rather want someone to sit over this overnight and fix this.

**Comment by pratyakshs** [comment]
If someone's working on the compatibility with nx 1.9.1: one bug seems to be when nx (in its code) tries to save the graph that was passed as argument. The statement is `subG = type(G) (G.edges_iter())`. Probably this leads to G being constructed again (by calling add_edge()) and causes an infinite loop. 
One hack to solve this is to pass the graph to (for example) nx.simple_cycles() as `nx.simple_cycles(nx.DiGraph(self))` rather than `nx.simple_cycles(self)`.

**Comment by ankurankan** [comment]
Issue with networkx version. Closing this.
