### ISSUE TITLE
Should string parameters be allowed in certain functions of the Factor class?

### ISSUE THREAD

**Issue by yashu-seth** [pgmpy/pgmpy#485]
Till now functions like get_cardinality, reduce, maximize and marginalize (in the factor class) do not take string parameters as input and throw a ValueError since it can take only type list or array-like parameters. I am currently working to display a proper TypeError message for such cases.
But now, I think string parameters should also be allowed. We can check for the type of the parameter and if being a type str we can convert it into a type list within the function itself.

**Comment by yashu-seth** [comment]
@ankurankan

**Comment by ankurankan** [comment]
@yashu-seth Earlier, we used to have the behavior that you are talking about. But we removed it because of optimization issues. The problem is that when running inference algorithms these methods are called thousands of times and the time spent on these checks start adding up. Also most of the time we already have a list, or array-like structure when calling these methods. That's why we removed it.

**Comment by ankurankan** [comment]
@yashu-seth Yes, it will. And I am not really in the favor of having those checks. But until we find a better solution to this, we will have to keep it like that.

**Comment by yashu-seth** [comment]
@ankurankan Okay. For now I will add the tests accordingly.

**Comment by yashu-seth** [comment]
@ankurankan Earlier a ValueError is thrown when string parameters are given. So can we put a check after encountering a ValueError case? I mean check for the type of the parameter only when the value error is encountered. This way we can change the type str parameter into type list and recall the function, if still the value error exists then we can display the error message else continue. This can save checking for the type of the parameter in every call and restrict it to only the  ValueError cases.

**Comment by yashu-seth** [comment]
@ankurankan Earlier a ValueError is thrown when string parameters are given. So can we put a check after encountering a ValueError case? I mean check for the type of the parameter only when the value error is encountered. This way we can change the type str parameter into type list and recall the function, if still the value error exists then we can display the error message else continue. This can save checking for the type of the parameter in every call and restrict it to only the  ValueError cases.

**Comment by ankurankan** [comment]
@yashu-seth I don't really feel like this is necessary. Since the `Factor` methods are mostly going to be an internal thing and users would hardly be interacting directly with those. So, I don't feel like having any checks for parameters (as we need these methods to be as fast as possible) in the method and handle all these things before these methods are called.
