### ISSUE TITLE
Creating visual models for PGM graphs. What would be an idea entry point to visualization?

### ISSUE THREAD

**Issue by pramttl** [pgmpy/pgmpy#7]
Should we have some sort of a BayseanModel obj.visualize() function that opens the browser for the user and renders the graph for him?

Any better idea?

**Comment by ankurankan** [comment]
@pramttl We were actually thinking of something like [SAIMAI](http://reasoning.cs.ucla.edu/samiam/) in which the user would be able to do everything interactively like create graph, assign CPD's, add observations etc. Since using the library directly from python requires a lot of effort having some interactive application would really simply it for the user.

**Comment by snigam3112** [comment]
@pramttl you could see the sample in Lecture 2-8
