### ISSUE TITLE
Separate state name features from the main code base

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#828]
We want the state name features to interact with the main codebase only by decorators. But there is one instance where we are using it explicitly in the code base: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/models/BayesianModel.py#L740. 

We need to find a solution to move this out.

**Comment by raghavg7796** [comment]
@ankurankan But @StateNameInit requires state_names to be passed in kwargs. So we will need to pass state_names argument.
One method can be to use state_names as variable in model rather than inference. This will solve two problems:
1. Inference can take state_names directly from model on which they are applied.
2. State_names are property of models. So a user can see states of the variables in the model.

**Comment by yashu-seth** [comment]
> Inference can take state_names directly from model on which they are applied.

But this would require making changes in the main Inference code base.

**Comment by raghavg7796** [comment]
@yashu-seth Yes, it would require a lot of changes in inference code. But I can't find another solution. @ankurankan @yashu-seth Do you have any other solution?
