### ISSUE TITLE
Recalculating CPDs of Bayesian Model

### ISSUE THREAD

**Issue by rodolfolottin** [pgmpy/pgmpy#898]
In softwares like Netika or Hugin, on running mode, if you change the CPDs of a node, the changes propagate to the others connected nodes modifying its parameters. I am making some manual tests just changing the cpd node values, but they dont propagate to the others. Like:

`
model.get_cpds()[0].values[1][0] += 0.01
`
`
model.get_cpds()[0].values[1][1] -= 0.01
`

Is there a way to do it using the Inference classes?

**Comment by ankurankan** [comment]
@rodolfolottin For propagating the values automatically, I think we will need to take some assumption about the model (eg: the joint distribution remains the same). We don't have any such functionality implemented in pgmpy but it shouldn't be too much work to do/add this.

**Comment by rodolfolottin** [comment]
@ankurankan Do you have any ideia for how it would work?

**Comment by ankurankan** [comment]
@rodolfolottin Assuming that you want to keep the distribution constant, and for a simple network like: `A ---> B`. And let's say you changed `P(A)` to `P'(A)`, you can simply use this: `P'(B|A) = P(A) * P(B|A) / P'(A)` where `P'(B|A)` is the new CPD for `B`. And pgmpy already has methods for doing product and division on `DiscreteFactor` (http://pgmpy.org/factors.html#discrete-factor), so you can directly use that. But since we don't have product and divide methods for `TabularCPD`, you will need to convert the `TabularCPD` objects to `DiscreteFactor` (http://pgmpy.org/factors.html#pgmpy.factors.discrete.CPD.TabularCPD.to_factor) and do the operations and convert it back. 

The code should roughly look something like this (I haven't tested it):
```python
A_factor = cpd_a.to_factor()
B_factor = cpd_b.to_factor()
A_new_factor = cpd_a_new.to_factor()
B_new_factor = A_factor * B_factor / A_new_factor
cpd_b_new  = cpd_b.copy()
cpd_b_new.values = B_new_factor.values
```
