### ISSUE TITLE
HillClimbSearch.estimate() error

### ISSUE THREAD

**Issue by KIMGEONUNG** [pgmpy/pgmpy#978]
### Subject of the issue

Hi.
I was just following the example for BN structure learning, and when I operate the exact same code, an error occurs

```
from pgmpy.estimators import HillClimbSearch

# create some data with dependencies
data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
data['A'] += data['B'] + data['C']
data['H'] = data['G'] - data['A']

hc = HillClimbSearch(data, scoring_method=BicScore(data))
best_model = hc.estimate()
print(best_model.edges())
```

The line having problem is [ best_model = hc.estimate() ]

The error message was as following

"TypeError :+1:  unsupported operand type(s) for += 'OutEdgeView' and 'list'

How can I solve this problem..?

* pgmpy version : 0.1.6
* Python version : 3.5
* Operating System : win8

**Comment by ankurankan** [comment]
@KIMGEONUNG I just tried running your code on my machine and it works fine. Could you please try updating pgmpy from github and check if that fixes the issue for you ?

**Comment by thierryherrmann** [comment]
@KIMGEONUNG I had the same issue. Done some tests and it turns out I had a version of networkx that was too recent. I've reverted it back to version 1.11 and it worked fine. At some point in the networkx versions, we get an OutEdgeView object, and this doesn't support the '+' operation. Earlier version of networkx returned a list, so pgmpy worked when concatenate those with '+'.
Dependencies are mentioned in https://github.com/pgmpy/pgmpy and networkx is clearly specified (I had missed that). For sure that's your problem too!

Also I was wondering why some examples didn't yield the same result as documented (e.g. example for StructureScore or HillClimbSearch). The reason is again the package versions. In particular I reverted back to the versions of pandas, numpy, scipy specified and then I obtained the same results.
